version: 2

build:
  os: ubuntu-22.04
  tools:
    pip:
      name: pip
    sphinx:
      name: sphinx
      configuration: Documentation/conf.py
python:
  version: "3.10"
  install:
    - method: pip
      path: .
