version: 2

build:
  os: ubuntu-22.04
  tools:
    - pip
    - sphinx

sphinx:
  configuration: docs/conf.py

python:
  version: 3.9
  install:
    - method: pip
      path: .
sphinx:
  configuration: Documentation/conf.py

python:
  version: 3.9
  install:
    - method: pip
      path: .
