# conf.py

# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = []

# The master toctree document.
master_doc = 'index'  # Change if your main file is named differently

# General information about the project.
project = 'GuardVision'
copyright = '2023, Mohamed Reda Nkira'
author = 'Mohamed Reda Nkira - Zouga Mouhcine'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
version = '0.1'  # Change to your project version
release = '0.1.0'  # Change to your project release

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = None

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages. See the documentation for
# a list of builtin themes.
html_theme = 'alabaster'  # You can change this to any Sphinx theme you prefer

# Output file base name for HTML help builder.
htmlhelp_basename = 'Documentation'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    'preamble': '',
}

# The name of an image file (relative to this directory) to place at the top
# of the title page.
latex_logo = None

# -- Options for manual page output ---------------------------------------

man_pages = [
    (master_doc, 'GuardVision', 'Documentation',
     [author], 1)
]

# -- Options for Texinfo output -------------------------------------------

texinfo_documents = [
    (master_doc, 'GuardVision', 'Documentation',
     author, 'GuardVision', 'Systeme de Surveillance',
     'Miscellaneous'),
]
